name: TerraformApply

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
    
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  IAM_ROLE: ${{ secrets.IAM_ROLE }}

permissions:
  id-token: write
  contents: read
  pull-requests: write  

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: CloneRepository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: github-actions-federation
          aws-region: ${{ env.AWS_REGION }}

  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: github-actions-federation
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.2"

      - name: Verify Terraform version
        run: terraform --version

      - name: Terraform init
        run: terraform init -input=false

#      - name: Force Unlock Terraform State (if needed)
#        run: terraform force-unlock -force 0a272ffa-cd11-a59a-ed94-8d6144936c7a

      - name: Terraform validation
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  approval:
    runs-on: ubuntu-latest
    needs: terraform_plan
    if: github.event_name == 'pull_request'  
    steps:
      - name: Request Approval
        uses: hmarr/auto-approve-action@v4 

  terraform_apply:
    runs-on: ubuntu-latest
    needs: approval
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE }}
          role-session-name: github-actions-federation
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
